### ISSUE TITLE
Microsoft.ProjectOxford.Vision.ClientException

### ISSUE THREAD

**Issue by AlexanderTodorovic** [Azure/LearnAI-Bootcamp#33]
Dear All,
unfortunately the Image Processing solution runs into an exception after starting with
`TestCLI.exe -process c:\learnai-bootcamp\lab01.1-computer_vision\resources\sample_images`

Thank you.
Alex

Below is the full stack.
`Processing Directory c:\learnai-bootcamp\lab01.1-computer_vision\resources\sample_images
Processing c:\learnai-bootcamp\lab01.1-computer_vision\resources\sample_images\Analysis_6.jpg
Error: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<AnalyzeImageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceHelpers.VisionServiceHelper.<>c__DisplayClass17_0.<<AnalyzeImageAsync>b__0>d.MoveNext() in C:\LearnAI-Bootcamp\lab01.1-computer_vision\resources\code\Finished-ImageProcessing\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceHelpers.VisionServiceHelper.<RunTaskWithAutoRetryOnQuotaLimitExceededError>d__13`1.MoveNext() in C:\LearnAI-Bootcamp\lab01.1-computer_vision\resources\code\Finished-ImageProcessing\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceHelpers.VisionServiceHelper.<AnalyzeImageAsync>d__17.MoveNext() in C:\LearnAI-Bootcamp\lab01.1-computer_vision\resources\code\Finished-ImageProcessing\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProcessingLibrary.ImageProcessor.<ProcessImageAsync>d__0.MoveNext() in C:\LearnAI-Bootcamp\lab01.1-computer_vision\resources\code\Finished-ImageProcessing\ProcessingLibrary\ImageProcessor.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestCLI.Program.<ProcessDirectoryAsync>d__4.MoveNext() in C:\LearnAI-Bootcamp\lab01.1-computer_vision\resources\code\Finished-ImageProcessing\TestCLI\Program.cs:line 110
`

**Comment by AlexanderTodorovic** [comment]
The Image Process solution expects that the Computer Vision is created in the West US region. After creating in West US all is fine. Would be great if the solution could have a second parameter in
the settings.json to specify a specific region
e.g. "Url": "https://japaneast.api.cognitive.microsoft.com/vision/v1.0"
Thank you.
